import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import products from "../products.json";
import Hero from "../components/Hero";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Hero />
        <div className={styles.headline}>
          <h2>Featured Products</h2>
          <Link href="/products">See All</Link>
        </div>
        <div className={styles.grid}>
          {products.map((product) => {
            return (
              <div className={styles.card} key={product.id}>
                <img src={product.image} alt={product.title} />
                <h3>{product.name}</h3>
                <p>{product.seller}</p>
                <p>${product.price}</p>
                <button>Add to Cart</button>
              </div>
            );
          })}
        </div>
      </main>
    </div>
  );
}
