import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import Hero from "../components/Hero";
import Product from "../components/Product";
// import AddToCart from "../components/AddToCart";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Resonance and Wonder</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <Hero />
        <div className={styles.headline}>
          <h2>Featured Products</h2>
          <Link href="/products">See All</Link>
        </div>
        <div className={styles.grid}>
          <Product />
        </div>
      </main>
    </div>
  );
}
